name: scan-actions

on:
#    schedule:
#      - cron: '0 0 * * *'
# Remove both comments to run this action on daily basis.
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Cache Go
        id: cache-go
        uses: actions/cache@v2
        with:
          path: /home/runner/go
          key: ${{ runner.os }}-go

      - name: Setting up ProjectDiscovery tools
        if: steps.cache-go.outputs.cache-hit != 'true'
        env:
          GO111MODULE: on
        run: |
          #go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          #go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
          go install github.com/projectdiscovery/katana/cmd/katana@latest
          go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
          go install -v github.com/tomnomnom/anew@latest
        shell: bash

      - name: Running Scanner
        run: |
          nuclei -update-templates
          #subfinder -silent -dL input/domains.txt -config config/subfinder-config.yaml | anew output/passive_subdomains.txt | httpx -silent | anew output/active_urls.txt | nuclei -silent -t takeovers/ | anew output/nuclei_output.txt
          anew domains.txt | katana -silent -d 5 -em json,jsp,php,html | anew scan_urls.txt | nuclei -silent -t cves/ | anew output.txt
        shell: bash

      - name: Sorting the output results
        run: |
          find output -type f -exec sort {} -o {} \;
        shell: bash

      - name: Create local changes
        run: |
          git add domains.txt
          git add scan_urls.txt
          git add output.txt

      - name: Commit results to Github
        run: |
          git config --local user.email "xxx@xxx.io"
          git config --global user.name "xxx"
          git commit -m "Scan-Actions report" -a --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
